### ISSUE TITLE
Getting error code 3001 while socket connetion

### ISSUE THREAD

**Issue by jadhavshital** [ARMmbed/mbed-mqtt#22]
Hi,
I have compiled the code using mbed-mqtt and mbed-os 5.14.2 for target FVP_MPS2_M7 for toolchain GCC_ARM. While running that elf file on simulator(FVP_MPS2_Cortex-M7.exe) it is giving en error as shown in screenshot below.
![socket error 3001](https://user-images.githubusercontent.com/17235485/80216179-4bcb9300-865b-11ea-8d49-5a1d68c85d9d.PNG)
I have referred https://os.mbed.com/docs/mbed-os/v5.15/apis/network-socket.html but didn't get any idea by reading "no data is not available but call is non-blocking".

Here is my main.cpp file.
[main.txt](https://github.com/ARMmbed/mbed-mqtt/files/4529088/main.txt)

Any help will be appreciated!

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/ONME-4500*

**Comment by michalpasztamobica** [comment]
Hi @jadhavshital ,

I can see in your code you set the socket into non-blocking mode:
```
net->set_blocking(false);
```
So when it can't connect or connection times out, it will report `WOULD_BLOCK` (-3001).
Did you start an MQTT broker locally and is it configured to run on port 1883, so that your client can actually connect to it?

Also, no need to call `gethostbyname()` if you have an explicit IP address, such as `127.0.0.1`. This function is only useful if you're resolving hostname via DNS for example, you're trying to connect to `www.mbed.com` and need to translate it to IP address. It shouldn't hurt though.

**Comment by jadhavshital** [comment]
Hi @michalpasztamobica,
I have tried by commenting 'net->set_blocking(false)' but it still wasn't working.
If I set bloking to true, still error code is -3001.

**Comment by michalpasztamobica** [comment]
```
const char* hostname = "127.0.0.1";
```
I suppose you're running MQTT server on some kind of a PC?
"127.0.0.1" will only work if you run your mqtt client on the same machine as your server. 
If you're running mqtt client on a separate device you must know your server's external IP address, given to it by the DHCP or set statically, something like "192.168.1.5" and use that address on your device. 
Could this be the issue?

**Comment by jadhavshital** [comment]
I was running MQTT broker and code on same machine but the simulator was taking it's own localhot, then I used IP address of my machine and then it worked for target FVP_MPS2_M3 but not for FVP_MPS2_M7. 

But yes, It solved my problem.

Thanks.
